spring:
   profiles:
      active: ${ACTIVE_PROFILE:develop}
   application:
      name: controle-ponto
   datasource:
      hikari:
         connectionTimeout: 20000
         maximumPoolSize: 10
         poolName: HikariPoolZZZ
      platform: postgresql
      url: jdbc:postgresql://${DATABASE_URL:localhost:5432}/${DATABASE_NAME:ponto}
      username: ${DATABASE_USERNAME:postgres}
      password: ${DATABASE_PASSWORD:teste}
   jpa: 
      show-sql: true
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.PostgreSQLDialect
   jackson:
      serialization:
         fail-on-empty-beans: false
server:
   port: ${PORT:8080}
   servlet:
      context-path: /controle-ponto/api

#swagger:
#   path_api_scan: br.gov.caixa.sisra
#   info:
#      title: SISRA Cadastro Cliente API
#      description: Módulo de Cadastro de Clientes do SICLI
#      version: '@project.version@'
#      termsOfServiceUrl: SISRA
#      contact: 
#         name: SISRA
#         url: SISRA
#         email: ceaus230@caixa.gov.br
#      license: https://www.caixa.gov.br
#      licenseUrl: www.caixa.gov.br

